name: "My CodeQL config"

disable-default-queries: true

queries:
  - name: Use an external JavaScript QL pack (run queries from an external repo)
    uses: octo-org/javascript-qlpack@main
  - name: Use an external query (run a single query from an external QL pack)
    uses: octo-org/python-qlpack/show_ifs.ql@main
  - name: Use a query suite file (run queries from a query suite in this repo)
    uses: /custom_query.ql

paths:
  - src 
paths-ignore: 
  - src/node_modules
  - '**/*.test.js'
